# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('mail', models.EmailField(max_length=254)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
