# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=30)),
                ('specialisation', models.CharField(max_length=30)),
                ('Degree', models.CharField(max_length=30)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=3)),
                ('start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myCV.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField(blank=True)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myCV.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=30)),
                ('Position', models.CharField(max_length=30)),
                ('Description', models.TextField(blank=True)),
                ('start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myCV.Person')),
            ],
        ),
    ]
