# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0002_education_skills_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
