# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0003_auto_20200707_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='ID',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='ID',
        ),
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
