# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0004_auto_20200707_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='ID',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='ID',
            new_name='person',
        ),
    ]
