# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCV', '0005_auto_20200707_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name_plural': 'Work'},
        ),
    ]
